### ISSUE TITLE
Missing tag for zeroize v1.7.0

### ISSUE THREAD

**Issue by paolobarbolini** [RustCrypto/utils#1060]
It looks like no tag has been made for the zeroize v1.7.0 release.

Could that tag be added now?
The exact git commit id can be found from https://docs.rs/crate/zeroize/1.7.0/source/.cargo_vcs_info.json

**Comment by tarcieri** [comment]
It's tagged, although the commit in this tree is df6d2f48a5e8afe8eef04ba32e2af55bacb41375

**Comment by paolobarbolini** [comment]
Thank you. Closing now
