### ISSUE TITLE
migration guide for block-padding 0.2.x to 0.3.x

### ISSUE THREAD

**Issue by sedan-cell** [RustCrypto/utils#1078]
looks like api changed and no migration guide present. can one be posted please as this upgrade broke a bunch of my code.

**Comment by newpavlov** [comment]
API surface of the crate is relatively small, so it should be relatively easy to migrate the crate by reading the new docs.

See this [comment](https://github.com/RustCrypto/block-ciphers/issues/425#issuecomment-2144043309) for more infromation.
