### ISSUE TITLE
Failing to build `cpufeatures` with rustc `--target=armv7-linux-androideabi`

### ISSUE THREAD

**Issue by cdesouza-chromium** [RustCrypto/utils#1086]
Hello there,

I'm not sure what arch it would be considered in this case, but when building for this configuration I'm getting the following build error:

```
error: This crate works only on `aarch64`, `loongarch64`, `x86`, and `x86-64` targets.
   --> ../../brave/third_party/rust/chromium_crates_io/vendor/cpufeatures-0.2.11/src/lib.rs:152:1
    |
152 | compile_error!("This crate works only on `aarch64`, `loongarch64`, `x86`, and `x86-64` targets.");
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 1 previous error
```

I would assum that this should fall under `aarch64`, and I'm not sure what `target_arch` becomes for that triple.

Claudio.

**Comment by newpavlov** [comment]
It's a `target_arch = "arm"` target. See #850 for more information about its support.
