### ISSUE TITLE
Custom Zeroize impl 

### ISSUE THREAD

**Issue by shriphani** [RustCrypto/utils#1140]
Hi folks, thank you very much for your work on this library. I have this type `PrivateKey` that is a container for `[GoldilocksField; KEY_LENGTH]`. Since `GoldilocksField` doesn't impl Zeroize, I did this. Is this sufficient? Do I need to do anything else like `#[inline(never)]` ?

```
#[derive(Debug, Copy, Clone)]
pub struct PrivateKey([GoldilocksField; KEY_LENGTH]);

impl Zeroize for PrivateKey {
    fn zeroize(&mut self) {
        for field in &mut self.0 {
            *field = GoldilocksField::ZERO
        }
    }
}
```

**Comment by newpavlov** [comment]
Such implementation is not sufficient. The compiler can remove such writes during optimizations. You need either to use [`zeroize_flat_type`](https://docs.rs/zeroize/latest/zeroize/fn.zeroize_flat_type.html) if you can guarantee that `GoldilocksField` is a "flat" type, or [`core::hint::black_box`](https://doc.rust-lang.org/beta/core/hint/fn.black_box.html). The latter works fine with the mainline compiler, but may become noop in alternative compilers.

**Comment by shriphani** [comment]
This is the GoldilocksField struct: `pub struct GoldilocksField(pub u64);` So I can do this I guess:

```
impl Zeroize for PrivateKey {
    fn zeroize(&mut self) {
        for field in &mut self.0 {
            unsafe {
                zeroize_flat_type(field);
            }
        }
    }
}
```
