### ISSUE TITLE
proc-macro-hack 0.5?

### ISSUE THREAD

**Issue by ignatenkobrain** [RustCrypto/utils#19]
It would be great if you would update proc-macro-hack dependency to latest 0.5 versions.

**Comment by newpavlov** [comment]
I plan to remove dependency on `proc-macro-hack` altogether and migrate to real procedural macros together with migration on 2018 edition, see #13.

**Comment by newpavlov** [comment]
I've tried to use `proc-macro` directly and unfortunately we still will have to use `proc-macro-hack`. Currently we get "procedural macros cannot be expanded to expressions (see issue rust-lang/rust#54727)".

**Comment by newpavlov** [comment]
I've published `hex-literal` v0.2.0 which uses proc-macro-hack 0.5.
