### ISSUE TITLE
[pkcs8] SPKI null-byte preceding key bytes

### ISSUE THREAD

**Issue by sebpuetz** [RustCrypto/utils#192]
Hi,

I'm trying to get the key bytes out of a public key in SPKI format but am getting unexpected results with a `0` preceding the key's bytes. Not really familiar with the matter so I might be misunderstanding something here.

I tried PEM and DER encoded public keys derived from a private key through:
~~~sh
openssl rsa -inform der -in rsa-2048-private-key.der -outform der -pubout > pub.pkcs8
openssl rsa -in rsa-2048-private-key.pem -pubout > pub.pem
~~~

~~~Rust
    let pkcs = pkcs8::PublicKeyDocument::from_der(&fs::read("testdata/pub.pkcs8").unwrap()).unwrap();
    let pkcs_bytes = pkcs.spki().subject_public_key;

    // using ring to get a keypair out of the private key file
    use ring::signature::KeyPair;
    use ring::signature::{RsaKeyPair, UnparsedPublicKey};
    let key = fs::read("testdata/rsa-2048-private-key.der").unwrap();
    let key_pair = RsaKeyPair::from_der(&key).unwrap();
    let pub_key = key_pair.public_key();
    
    assert_eq!(pub_key.as_ref(), &key2.spki().subject_public_key); // fails
    assert_eq!(pub_key.as_ref(), &key2.spki().subject_public_key[1..]); // works

    // using the pem crate to parse the key
    let key = pem::parse(&pub_key2).unwrap();
    assert_eq!(pub_key.as_ref(), &key.contents[24..]) // manually skipping the header works, too
~~~

I can decode the key here: https://lapo.it/asn1js/#MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArdF_BiYKSDz0urb6edkdrjWYyYhI02jZw8dpIy8iezVVqZmOPo9ya6dxYDp23ldZ5f5wrFA3kgGVymPcme-gw92MlmBy4mGF1EEpbQ4WKJjxtFmpHe75H0mSj4AwsfWuFDcuAGim0tG0ba_ufV1ySOvJYypqULa9brr0Rcg8SkS-EW317pXOF4TJlqSlKdAlHnvsZbQkU7lyLSsGgt-Somhlew5mmQhtiJ-jtXqXEtJyFBMpokBwScR0UhieL8hKTB6h5c2EgaC8NXSjhPvkJIjwykgy_zFuj91V-Oz2vX3_R6mogyEyP8McPfCvGDJ7KwhvvnO0B-NG2I3lwQDKfpWTTKGiCvvD2NM2ICWopKkDSj_Tqp6nqCyxdgR35IjsP4XcWyA9I4PggE4PYPB6yrewfvCsUMXAUB-VIPZJr8bSeZBj044vLbhHu0rOTTZkkcRBK2Iqd6w5ZJjuFRGrc4_PBJh_6lKVTbfR7_JvLzVChvhLWLwy1LHr88RLiK1bJuMa1Z7070m5Bbe13E4aNqUAaTUriro8UWVbHE0QRubym3as24u2013xt6Z5G7Iz_F-yJbU3H3UyxjjxgVDQQKbNOrhCWld--G_zynuW6HepJfTrYcSt4JSan2gbaMV-0HO9vCK-nKKrF7slLwX4YXaYbLwXI3MJrKytg3yRan8CAwEAAQ

which highlights the `0`-byte at the end of the `BitString` header. Digging a bit into `ASN.1` documentation, it seems that byte denotes the number of unused bits in the `BitString`, which `DER` requires to be 0: https://letsencrypt.org/docs/a-warm-welcome-to-asn1-and-der/#bit-string-encoding. Is it expected to include this byte in the `subject_public_key` while excluding the rest of the `BitString` header?

I'm running into this issue while retrieving PEM / SPKI encoded keys from a DB to verify a signature with `ring`, so I can't just change the format of the keys through `openssl` as the `ring` documentation suggests to do.

**Comment by tarcieri** [comment]
Yes, right now it's included. I've debated about whether it makes sense to strip it in the PKCS#8 crate itself or not, versus providing the `BIT STRING`.

It definitely could, although that would be a breaking change.

**Comment by sebpuetz** [comment]
Certainly caused a lot of head scratching for me, I first went down a wrong path and assumed it was about `ASN.1`'s Integer encoding. Maybe a comment in the docs could make this a bit clearer?

Is my usage with skipping the first byte what you'd expect to see with this API?

**Comment by tarcieri** [comment]
This should take care of it, but will need another breaking release: https://github.com/RustCrypto/utils/pull/193

**Comment by tarcieri** [comment]
I released `pkcs8` v0.4.0-pre which depends on a prerelease of `der` which includes the above commit which strips the leading `0x00` byte.

Let me know if that addresses your problem.

**Comment by sebpuetz** [comment]
Gave it a go, seems to work as expected!

**Comment by tarcieri** [comment]
Awesome. Will go ahead and close this out then.
