### ISSUE TITLE
Padding requires too much overhead

### ISSUE THREAD

**Issue by sebastianv89** [RustCrypto/utils#20]
The first encryption example on the README page is somewhat counter-intuitive: the 12-byte message `b"Hello world!" is encrypted to 16 bytes, but the buffer must be 24 bytes (it is actually 32 bytes in the example).

It turns out that none of the bytes `buffer[16..]` are ever read or even used for intermediate computations. Instead, the `block_padding::Padding` trait has a default method `pad` that requires `buf.len() - pos >= block_size`. This can result in a `PadError` despite there being enough space for the padding.

**Comment by newpavlov** [comment]
I've published `block-padding` v0.1.4 with your update!
