### ISSUE TITLE
dbl: remove unsafe code

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/utils#215]
Currently `dbl` uses `unsafe` code only for converting byte arrays to `[u64; N]` and back. We probably should change API in a such way which would allow us to remove it, e.g. by working on `u32` and/or `u64` arrays.

**Comment by tarcieri** [comment]
I'm a bit confused why `dbl` is complex as it is.

AFAIK it's used by CMAC, PMAC, and AES-SIV (for S2V), all of which are GF(2^128) and use a common polynomial with a big endian field element encoding.

Yet for some reason it's generic over some additional field element sizes which AFAIK we don't use. It doesn't, however, allow you to supply a different polynomial or use a little endian field element encoding, which would be needed to [use it for `mulX_POLYVAL`](https://github.com/RustCrypto/universal-hashes/blob/7d01b6d/polyval/src/mulx.rs#L12-L19) for example.

**Comment by newpavlov** [comment]
Resolved in #688
