### ISSUE TITLE
block-buffer yanks

### ISSUE THREAD

**Issue by ignatenkobrain** [RustCrypto/utils#22]
I could not find reason why it was yanked. Could you provide some information, please?

Thanks!

**Comment by newpavlov** [comment]
They had `input2` method which [used](https://docs.rs/block-buffer/0.7.2/src/block_buffer/lib.rs.html#61-91) `slice::from_ref` method. I've missed the fact that it was stabilized only in Rust 1.28, so those versions broke [MSRV contract](https://github.com/RustCrypto/hashes#minimum-supported-rust-version-msrv). In near future I plan to migrate crates to 2018 edition, so this method will be added at that time.

**Comment by ignatenkobrain** [comment]
Ah. Thanks for the answer. I'll keep the latest version shipped in Fedora because we always ship latest compiler so we don't care about that.

Thanks again for input!
