### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by AurevoirXavier** [RustCrypto/utils#27]
```shell
λ rustc --version
rustc 1.38.0-nightly (311376d30 2019-07-18)
```

```rust
error: proc-macro derive panicked
  --> /Users/xavier/.cargo/registry/src/github.com-1ecc6299db9ec823/hex-literal-0.1.4/src/lib.rs:38:1
   |
38 | / proc_macro_expr_decl! {
39 | |     /// Macro for converting hex string to byte array at compile time
40 | |     hex! => hex_impl
41 | | }
   | |_^
   |
   = help: message: assertion failed: `(left == right)`
             left: `Some("#[allow(unused,")`,
            right: `Some("#[allow(unused")`
   = note: this warning originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

**Comment by newpavlov** [comment]
Can you check with the latest nightly? Everything works for me on 2019-07-19 nightly.

**Comment by boneyard93501** [comment]
same problem for 2019-07-20
```
boneyard93501@mbp15 ~ $ rustc --version
rustc 1.38.0-nightly (95b1fe560 2019-07-20)
```  

with  
  
```
error: proc-macro derive panicked
  --> /Users/boneyard93501/.cargo/registry/src/github.com-1ecc6299db9ec823/hex-literal-0.1.4/src/lib.rs:38:1
   |
38 | / proc_macro_expr_decl! {
39 | |     /// Macro for converting hex string to byte array at compile time
40 | |     hex! => hex_impl
41 | | }
   | |_^
   |
   = help: message: assertion failed: `(left == right)`
             left: `Some("#[allow(unused,")`,
            right: `Some("#[allow(unused")`
   = note: this warning originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error
```

**Comment by newpavlov** [comment]
Hm, I still can't reproduce it on Linux. I've re-run nightly CI for hashes and it has passed without any issues. Do you build `hex-literal` directly or as part of your project? Do you use Windows?

Looks like the error originates from [here](https://github.com/dtolnay/proc-macro-hack/blob/0.4.2/impl/src/lib.rs#L71), but I don't know what exactly causes it.

@dtolnay
Any ideas?

**Comment by boneyard93501** [comment]
@newpavlov 
you just beat me to it. it's part of a project build and i followed:
https://github.com/paritytech/substrate/issues/3134
however, after some fiddling i found a 0.1 reference in https://github.com/substrate-developer-hub/substrate-package/blob/master/substrate-node-template/Cargo.toml#L11
if you bump L11 from 0.1 to 0.2 and then rebuilding the respective Cargo.lock files ends up compiling 0.1.4 just fine.
so, apologies for given you the run around; i shouldn't have just taken the assertion in #3134 at face value.

**Comment by AurevoirXavier** [comment]
It seems the same problem. A part of [darwinia](https://github.com/darwinia-network/darwinia) which build on substrate.
