### ISSUE TITLE
base64ct: `if` is not allowed in a `const fn`

### ISSUE THREAD

**Issue by ctzurcanu** [RustCrypto/utils#326]
/base64ct-0.2.0/src/encoding.rs:300:5

How did you get this to compile ok? Should this be included in the docs?

**Comment by tarcieri** [comment]
This crate is MSRV 1.46+, however it looks like that's incorrectly reflected in the version badge and we don't have the same sort of [MSRV statement we normally have in other crates](https://docs.rs/der/0.2.10/der/#minimum-supported-rust-version), so yes, the docs are missing/out-of-date for this.

**Comment by ctzurcanu** [comment]
that helped. I will leave this open to remind you to fix this in the badge or docs.
