### ISSUE TITLE
block-padding does not provide a "no padding" implementation

### ISSUE THREAD

**Issue by robeady** [RustCrypto/utils#34]
I found it rather puzzling that this library does not provide a no-op / no padding implementation, requiring the user to do it themselves. I expected to find one since rust-crypto does provide this.

**Comment by zer0x64** [comment]
+1, had the exact same problem trying to implement a protocol I didn't write. Also, some operation like key wrapping might actually require a NoPadding option for legit purposes. Right now, the "best available option" is to use ZeroPadding and check it the size is a mutliple of the block size to re-pad it in case the value actually ends with zeroes.

**Comment by newpavlov** [comment]
@robeady 
Does #37 address your needs?

**Comment by robeady** [comment]
I believe it does, thanks :)

The problem with ZeroPadding is that it would remove trailing zeros from blocks when unpadding. I initially assumed that zero padding meant no padding which caused some confusion lol

**Comment by newpavlov** [comment]
>The problem with ZeroPadding is that it would remove trailing zeros from blocks when unpadding.

Ah, yes. You are right.
