### ISSUE TITLE
How to use blobby for test vectors?

### ISSUE THREAD

**Issue by Slals** [RustCrypto/utils#38]
Hey guys,

I noticed you used blob files to test vectors as in here : https://github.com/RustCrypto/block-ciphers/tree/master/aes/aesni/tests/data

I supposed you used [blobby](https://github.com/RustCrypto/utils/tree/master/blobby) to do that. If so how do you convert [this](https://www.cosic.esat.kuleuven.be/nessie/testvectors/) to a blob?

**Comment by clintnetwork** [comment]
Hmm good question, @newpavlov any idea?

**Comment by newpavlov** [comment]
`blobby` file format is a simple stream of binary blobs without any structure. This stream is then interpreted by `Blob2Iterator`, `Blob3Iterator` and `Blob3Iterator` to get pairs, triplets, quintuplets respectively. In other words, if we have blobs `[b1, b2, b3, b4, b5, b6]` inside a file, `Blob2Iterator` will return `[(b1, b2), (b3, b4), (b5, b6)]`. And depending on structure of test vectors those types are used by [testing macros](https://github.com/RustCrypto/traits/blob/master/digest/src/dev.rs#L5).

To convert from a text format you can use [the `convert` example](https://github.com/RustCrypto/utils/blob/master/blobby/examples/convert.rs) after some pre-processing. `cargo run --example convert -- encode input.txt output.blb` will convert hex-encoded binary blobs in the input file, for example with [MD5 test vectors](https://www.cosic.esat.kuleuven.be/nessie/testvectors/hash/md5/Md5-128.unverified.test-vectors), first lines of `input.txt` will look like this:
```

D41D8CD98F00B204E9800998ECF8427E
61
0CC175B9C0F1B6A831C399E269772661
616263
900150983CD24FB0D6963F7D28E17F72
6D65737361676520646967657374
F96B697D7CB7938D525A2F31AAF161D0
```
Note the first empty line, it means that first blob in the stream in the output stream will an empty one.

**Comment by Slals** [comment]
Thanks @newpavlov it helps a lot. Do you use any tool for pre-processing the plain text test vectors in  order to get the hex as in your example?

**Comment by newpavlov** [comment]
@Slals 
Usually I either copy test vectors by hand if they are small enough and already given in the hex form, or write a simple Python script to do the conversion. I had such script for NESSIE vectors, but I can't find it now. If you plan to submit PR with an algorithm implementation, you can do it without using the blobby format, I can always add such tests later.

**Comment by Slals** [comment]
Understood. I just noticed how the test vectors where pre-processed. Thanks again I'll find my way out with the informations you provided. I close the issue.
