### ISSUE TITLE
Feature request, allow comments in hex-literal::hex macro

### ISSUE THREAD

**Issue by alan-signal** [RustCrypto/utils#511]
I would like to be able to use comments like so:

```rust
   hex!(
       "
        // header
        0001 006c 2112a44238656d797950694b78506e6e
        // username
        0006 0025 63636431623031363037000000
        // etc
        c057 0004 00010032 // or here
     ");
```

As `/` is not currently a valid character, it could be added without causing any breaking changes.

`//` would just mean ignore all characters until the next line.

If you are open to this idea, I am happy to make a PR.

**Comment by tarcieri** [comment]
There’s an open PR for this: #365 

However, it’s stalled on the syntax. We wanted the syntax you suggest (standard Rust/C++ style comments), but that PR used # instead.

If you opened a PR that implements standard Rust style comments, I think we’d merge it.

**Comment by alan-signal** [comment]
Thanks @tarcieri , so do you think it should accept `/* */` style as well as `//`?

I have no problem going the whole hog and I can absolutely see the value in that over end-of-line only.

```rust
   hex!(
       "
        /* header   */ 0001 006c 2112a44238656d797950694b78506e6e
        /* username */ 0006 0025 63636431623031363037000000
        // etc
     ");
```

**Comment by tarcieri** [comment]
I think `//` is good enough to start with. Looking at #365 the other unaddressed concerns were a lack of tests

**Comment by alan-signal** [comment]
Oh yes, there will be tests and docs :)
