### ISSUE TITLE
hex-literal: accept list of literals?

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/utils#518]
Right now, if we are to write code like this:
```rust
hex1!("
    AABBCCDD
    00112233
");
```
`rustfmt` transforms it into:
```rust
hex1!(
    "
    AABBCCDD
    00112233
"
);
```

Frankly it's really annoying, but I don't think we will get a fix on the `rustfmt` side. I know that there is a workaround:
```rust
hex!(
    "AABBCCDD
     00112233"
);
```
But to me personally it looks a bit weird.

So how about we will extend the `hex!` macro to allow list of literals which would be concatenated after decoding? Not only it would help with the formatting issue, but also would allow to add comments which would be properly highlighted in IDEs, unlike the extension added in #512:
```rust
hex!(
    "AABBCCDD" // comment
    "00112233"
);
```

What do you think? It looks like this change should be completely backwards compatible.

**Comment by tarcieri** [comment]
Sounds good to me
