### ISSUE TITLE
base64ct doesn't check for "invalid padding"

### ISSUE THREAD

**Issue by The-King-of-Toasters** [RustCrypto/utils#575]
Background: I'm currently writing my own base64 and PEM decoder in Zig and I'm basing my work on yours. I've been testing my implementation against the [Zig stdlib's](https://github.com/ziglang/zig/blob/master/lib/std/base64.zig) and notices some irregularities.

This implementation and the original by Sc00bz (along with some other ones I tested[1]) seem to be too accepting of encoded input. For example, the octet `0x1f` is `Hw`/`Hw==` after encoding. However, if you pass the string `H(x|y|z)(==)?` to the decoder, it'll happily decode it as `0x1f`. In other decoders[2], this produces an error - in Zig's case it returns `InvalidPadding`. I'm unsure if this happens because of the total lack of a LUT.

[1]: coreutils `base64 -d`, Go stdlib
[2]: libsodium, OpenBSD `b64decode -r`/b64_pton, Zig stdlib, base64 crate, radix64 crate.

**Comment by The-King-of-Toasters** [comment]
Here's some more bad decodes from the Zig stdlib:
- `AA/=` -> [0x00, 0x0f], should be `AA8=`.
- `A/==` -> 0x03, should be `Aw==`.

**Comment by tarcieri** [comment]
Thanks for reporting this.

A possible workaround is to attempt to round-trip the decoded data back to the padded form and ensure it matches.

It's possible there's also a more elegant solution /cc @Sc00bz

**Comment by tarcieri** [comment]
Released as v1.0.1

**Comment by ilovelll** [comment]
One of my test case `B2C=` failed to decode after upgrade to v1.0.1, is it correct?

**Comment by tarcieri** [comment]
That would appear to be the bytes `[0x07, 0x60]` which are properly encoded as `B2A=`.

Likewise the `base64` crate returns: `InvalidLastSymbol(2, 67)`
