### ISSUE TITLE
`BlockBuffer::pad_with` exposes uninitialized memory through safe API

### ISSUE THREAD

**Issue by kazcw** [RustCrypto/utils#6]
`Padding::pad` is not a safe function. A correct implementation must not read the initial value of anything in `data[pos..]`, and must write to everything in `data[pos..]` before returning.

**Comment by newpavlov** [comment]
Sorry for the late reply!

`Padding::pad` can't expose uninitialized memory as data slice is provided by the caller, thus it should be already fully initialized. So while correct implementation should indeed behave as you've described, it's not a memory safety issue. Thus I will close this issue.

BTW I will soon change padding API, as the current one is not expressive enough for some use-cases.
