### ISSUE TITLE
Contributing iso-10126

### ISSUE THREAD

**Issue by unbrice** [RustCrypto/utils#613]
Dear maintainers, I wish to contribute the support for [iso-10126](https://en.wikipedia.org/wiki/Padding_(cryptography)#ISO_10126). It is basically a variation of `Pkcs7` or `AnsiX923` where arbitrary bytes are used to fill the buffer, except for the last byte. Would you accept such a contribution?

Context: ISO 10126 was withdrawn in 2007 but is still being used in some context, including in [XML enc](https://www.w3.org/TR/xmlenc-core1/#sec-Padding).

Considered alternatives for the "arbitrary padding bytes":
1. `0x00` like `AnsiX923`
2. last byte like `Pkcs7`
3. Something else to minimise confusion.

I am leaning towards (3), to help prevent confusion.
I am proposing `(len(buffer)+10126)%256`, such that it is deterministic yet users are less likely to confuse it with `PKCS#7` or `AnsiX923` or any other standard. On unpadding the ignored bytes would be ignored.

**Comment by tarcieri** [comment]
What's the existing precedent in terms of how it's related with regard to these options?

**Comment by unbrice** [comment]
It's not my field of expertise so I can't state anything with a high confidence. If there is a consensus I have not been able to unearth it.
I did a survey of git repos mentioned [https://github.com/XML-Security/implementations](here). Unfortunately most of them seemed to only support checking signatures and not encryption. I also searched on the web for documentation on closed-source implementations.

With these caveats in mind:

- [This closed source impl (cryptosys.net)](https://www.cryptosys.net/pki/manpki/pki_paddingschemes.html) states it uses "PKCS#5" (really PKCS#7)
- [apache/santuario-xml-security-java](https://github.com/apache/santuario-xml-security-java) seems to use [null bytes](https://github.com/apache/santuario-xml-security-java/blob/521d93b86e08ea13a9c9580dc82d5111a50728fa/src/main/java/org/apache/xml/security/utils/XMLUtils.java#L989)
- [lsh123/xmlsec](https://github.com/lsh123/xmlsec) seems to use strong random bytes ([with mscrypto](https://github.com/lsh123/xmlsec/blob/4b6ab2d86b71f8642f19ab3b7a0777984b6bce9a/src/mscrypto/ciphers.c#L277), [with OpenSSL](https://github.com/lsh123/xmlsec/blob/4b6ab2d86b71f8642f19ab3b7a0777984b6bce9a/src/openssl/ciphers.c#L423-L429))
- IIUC [auth0/node-xml-encryption](https://github.com/auth0/node-xml-encryption) [uses whatever NodeJS uses](https://github.com/auth0/node-xml-encryption/blob/7b360cdeffbc41cc9785e17d59dbcb65189dc357/lib/xmlenc.js#L262) which IIUC is [whatever V8 uses](https://github.com/nodejs/node/blob/2de139b5d5ce49d11915dec095e833af60564317/lib/internal/crypto/aes.js#L148-L158) which in turn seems to be [PKCS#7](https://crypto.stackexchange.com/questions/10522/openssl-padding)

I have not been able to find strong technical reason for using any of these over another, so I'm thinking to go with intuition about general software good practices. Thus, other things being equal I am thinking that having a deterministic output is good, and that preventing confusion with another format is good hence my initial suggestion. Or if we go with the majority it would be PKCS#7.

**Comment by tarcieri** [comment]
I'd weakly be in favor of using PKCS#7 padding in that case
