### ISSUE TITLE
zeroize: implement `Zeroize` for `PhantomData`/`PhantomPinned`

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/utils#651]
Originally filed by @Allen-Webb as https://github.com/iqlusioninc/crates/issues/651

> Since often pinning is desired in conjunction with `Zeroize`, it would be nice to have `zeroize` define a `Zeroize` implementation for `core::marker::PhantomPinned` so that derive can be used with structs that contain `PhantomPinned` to prevent moving.

Originally filed by @daxpedda as https://github.com/iqlusioninc/crates/issues/899

> Sometimes, when you want to implement `Zeroize` for a structure that contains a `PhantomData` field, it's necessary to implement `Zeroize` by hand. I suggest improving this by simply implementing `Zeroize` for `PhantomData`, which should be no-op, as this has no representation data wise I believe.
>
> Alternatively, the derive proc-macro could detect `PhantomData` and skip it. I prefer the above solution though.

**Comment by daxpedda** [comment]
@tarcieri, this can be closed, right?
