### ISSUE TITLE
zeroize_derive: `Enum` without data is no-op

### ISSUE THREAD

**Issue by daxpedda** [RustCrypto/utils#702]
I noticed that an enum like this:
```rust
#[derive(Zeroize)]
enum Test {
  A = 0,
  B,
}
```
doesn't work like intended, it basically does nothing on `zeroize()`. How bad is this?

To fix this I propose to either disallow it or introduce a `#[zeroize(zero)]` attribute. It's a bit tricky because either way it's a breaking change.

```rust
#[derive(Zeroize)]
enum Test {
  A(u32),
  B,
}
```
What should `Test::B.zeroize()` do for example? Currently it does nothing, which I guess is fine?

Alternatively we could require `#[zeroize(zero)]` on every enum with more then one variant. Or we keep the current behaviour but document it somewhere.

**Comment by tarcieri** [comment]
Yes, it's true. The current enum zeroization is focused on zeroizing the fields of the enum variants and wasn't designed with the idea that the selected variant itself is sensitive.

I'm not sure there's a great way to handle this. It seems to run aground of the same problems of a declarative `Default` for enums which have stalled the custom derive work there.

**Comment by tarcieri** [comment]
Probably the best way to fix this is to not use the custom derive, but instead impl `DefaultIsZeros`, which will take care of overwriting the enum with its `Default`.
