### ISSUE TITLE
Fix MSRV tests for blobby and cpuid-bool

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/utils#71]
The new lock format was introduced in Rust 1.41, so older versions can not read it. Should we re-generate lock files for MSRV tests or simply test only for Rust 1.41 (thus effectively making it MSRV for those crates, even though they should work on earlier versions)?

**Comment by tarcieri** [comment]
FWIW, the merge-friendly lockfile format shipped in Rust 1.39

**Comment by newpavlov** [comment]
Hm, interesting, [RELEASES](https://github.com/rust-lang/rust/blob/master/RELEASES.md#cargo-4) indicate that this change was part of Rust 1.41.0, but I guess optional support was added earlier.

**Comment by tarcieri** [comment]
I think 1.41 might've been when it was made the default?
