### ISSUE TITLE
v1.5.1 cannot be downloaded from crates.io

### ISSUE THREAD

**Issue by sdlarsen** [RustCrypto/utils#722]
Cargo times out and the README is not visible on crates.io either. From the looks of it that times out as well (guessing here)

**Comment by tarcieri** [comment]
Works for me:

```
$ cargo build
    Updating crates.io index
  Downloaded zeroize v1.5.1
  Downloaded 1 crate (17.1 KB) in 0.30s
   Compiling zeroize v1.5.1
   Compiling zeroize-test v0.1.0 (/private/tmp/zeroize-test)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 18s
```

I also see the README.md:

<img width="958" alt="Screen Shot 2022-01-27 at 8 45 34 AM" src="https://user-images.githubusercontent.com/797/151393139-4880a04b-8fb0-46e1-a3f9-89c2c57abf6d.png">

Try again maybe?

**Comment by sdlarsen** [comment]
Oh I have tried a number of times. Must be some kind of network issue. Sorry to bother you with this, it might resolve itself overnight. Calling it a day is overdue anyway :)
