### ISSUE TITLE
cpufeatures: Use getauxval for aarch64 Android as well

### ISSUE THREAD

**Issue by jrose-signal** [RustCrypto/utils#751]
`libc::getauxval` was added for Android in rust-lang/libc#1987, and is available on all aarch64 Android devices, so we should be able to detect features there as well.

**Comment by tarcieri** [comment]
Mind submitting a PR for this? I've never used Rust on Android before

**Comment by jrose-signal** [comment]
Now I have to be the one to double-check that its results are the same as Linux. :-) Hang on…
