### ISSUE TITLE
Serde Serialize and Deserialize trait impls for Zeroizing, opt-in using crate feature?

### ISSUE THREAD

**Issue by vdods** [RustCrypto/utils#762]
Hi there, I'm wondering if it would be palatable to have the Zeroizing struct optionally (based on a crate feature) derive serde::Serialize and serde::Deserialize?  It would simplify a lot of downstream code.

**Comment by tarcieri** [comment]
I don't think it makes sense to couple `zeroize` and `serde` that way.
