### ISSUE TITLE
To use cpuid in SGX

### ISSUE THREAD

**Issue by ChuanDou2021** [RustCrypto/utils#784]
In SGX, just return `false` seems crude for some instructions.
There is a plan to use `cpuid` in SGX: [Trusted CPU Feature Detection Library for Intel® Software Guard Extensions (Intel® SGX)](https://github.com/intel/sgx-cpu-feature-detection/blob/master/README.md) .

**Comment by tarcieri** [comment]
You can override the `false` using target features.

Do any extant CPUs actually support invoking CPUID from SGX? Unless they do, we don’t exactly have a lot of options

**Comment by ChuanDou2021** [comment]
> You can override the `false` using target features.
> 
> Do any extant CPUs actually support invoking CPUID from SGX? Unless they do, we don’t exactly have a lot of options

**Comment by ChuanDou2021** [comment]
After some research, I got a conclusion: it's not recommended invoke `cpuid` in sgx, but rather a supplement. 
I will fork the crate, make customized modifications.
Thanks for your reply.
