### ISSUE TITLE
MSRV on `cpufeatures` broken by nightly cargo bug

### ISSUE THREAD

**Issue by TheBlueMatt** [RustCrypto/utils#795]
When trying to build something that depends on cpufeatures on rustc 1.48, I get the following error from cargo. This appears to be an instance of https://github.com/rust-lang/cargo/issues/10954, which means the cpufeatures crate simply needs to be re-uploaded with stable cargo (or a newer nightly).

```
error: failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/cpufeatures-0.2.3/Cargo.toml`

Caused by:
  feature `resolver` is required

  consider adding `cargo-features = ["resolver"]` to the manifest
```

**Comment by newpavlov** [comment]
Hm, it's weird that this issue did not trigger CI in the [hashes repository](https://github.com/RustCrypto/hashes) which has MSRV 1.41. Either way, I will release v0.2.4 using the stable 1.63 toolchain right away. Can you confirm that v0.2.4 fixes your issue?

**Comment by striezel** [comment]
> Can you confirm that v0.2.4 fixes your issue?

I got the same issue as @TheBlueMatt, and for me cpufeatures 0.2.4 fixes the issue. Version 0.2.4 builds with rustc 1.48.
