### ISSUE TITLE
hex-literal: allow use `|` to start comment?

### ISSUE THREAD

**Issue by hismito** [RustCrypto/utils#813]
```rust
hex!(
    "
    31 0a 32 0a 33 0a 34 0a  35 0a 36 0a 37 0a 38 0a  |1.2.3.4.5.6.7.8.
    39 0a 31 30 0a                                    |9.10.
    "
);
```

It's pretty common to separates hex and ascii by `|`,  this would enable copy-paste without any modification.

**Comment by tarcieri** [comment]
Personally I'd prefer to keep the number of comment syntaxes to a minimum for the sake of not overcomplicating the implementation

**Comment by newpavlov** [comment]
I agree. IIRC we declined request to support `#` for comments, so I don't think we should accept `|`l. Honestly, it may be worth to even completely forbid comments inside literals and instead recommend to use standard Rust comments with multi-literal `hex!`. Your example would look like this:
```rust
hex!(
    "31 0a 32 0a 33 0a 34 0a  35 0a 36 0a 37 0a 38 0a"  // 1.2.3.4.5.6.7.8.
    "39 0a 31 30 0a"                                    // 9.10.
);
```

**Comment by tarcieri** [comment]
FWIW there are several things that use the existing comment syntax. I would prefer not adding churn to remove it.

**Comment by newpavlov** [comment]
Well, `hex-literal v0.3` will continue to work without any changes, so people who don't want to edit comments can simply continue to use it.

Advantages of forbidding comments inside literals:
- Comments will be properly highlighted in code editors
- Significant simplification of the `hex-literal` code

`hex-literal` is quite stable, so it may be worth to consider releasing v1.0 sometime next year (though, ideally, I would like to get MSRV-dependent dependency version resolution before that).

**Comment by newpavlov** [comment]
Since we both agree regarding the OP's proposal, I will close this issue and will open a separate one for discussing potential v1.0 release.
