### ISSUE TITLE
What's aarch64 feature?

### ISSUE THREAD

**Issue by oilel** [RustCrypto/utils#833]
After running "cargo add zeroize":
Updating crates.io index
      Adding zeroize v1.5.7 to dependencies.
             Features:
             + alloc
             - aarch64
             - derive
             - serde
             - std
             - zeroize_derive

The aarch64 isn't found in document.

**Comment by newpavlov** [comment]
The `aarch64` feature adds zeroization [support](https://github.com/RustCrypto/utils/blob/master/zeroize/src/aarch64.rs) for AArch64-specific types.
