### ISSUE TITLE
only traits defined in the current crate can be implemented for types defined outside of the crate

### ISSUE THREAD

**Issue by oilel** [RustCrypto/utils#834]
error[E0117]: only traits defined in the current crate can be implemented for types defined outside of the crate
  --> src/main.rs:18:1
   |
18 | impl ZeroizeOnDrop for TcpStream;
   | ^^^^^^^^^^^^^^^^^^^^^^^---------
   | |                      |
   | |                      `async_std::net::TcpStream` is not defined in the current crate
   | impl doesn't use only types from inside the current crate
   |
   = note: define and implement a trait or new type instead

error[E0117]: only traits defined in the current crate can be implemented for types defined outside of the crate
  --> src/main.rs:19:1
   |
19 | impl ZeroizeOnDrop for TcpListener;
   | ^^^^^^^^^^^^^^^^^^^^^^^-----------
   | |                      |
   | |                      `async_std::net::TcpListener` is not defined in the current crate
   | impl doesn't use only types from inside the current crate

TcpStream and TcpListener are defined in async_std crate.

**Comment by newpavlov** [comment]
It's orphan rules working as expected. You should zeroize only sensitive data, which `TcpListener` is not (under the hood it's simply a file descriptor).
