### ISSUE TITLE
Missing `Copy` implementation for `<N as ArraySize<T>>::ArrayType`

### ISSUE THREAD

**Issue by huitseeker** [RustCrypto/utils#849]
`[T; N]` for any `const N` implements `Copy`:
https://github.com/rust-lang/rust/blob/f177b7cb91acd9debd1ed974e6521edb2ab6b097/library/core/src/array/mod.rs#L397-L398

And it is clearly the intent of this crate to use precisely this implementation for all instances of `<N as ArraySize<T>>::ArrayType`:
https://github.com/RustCrypto/utils/blob/bb022c838c12516659d10c4c9ae1d29a69ee0844/hybrid-array/src/lib.rs#L160-L162

Yet the constraint does not carry through `ArrayType`:
https://github.com/RustCrypto/utils/blob/master/hybrid-array/src/lib.rs#L111

This in turn prevents deriving `Copy` on any struct that includes some `ArraySize<T>`, since an instance of `Copy` isn't manually implementable.

**Comment by tarcieri** [comment]
What was the issue here?

**Comment by huitseeker** [comment]
Nothing, my mental wires crossed for a minute.
