### ISSUE TITLE
Use hex-literal to parse file containing hex string

### ISSUE THREAD

**Issue by Evian-Zhang** [RustCrypto/utils#85]
For now, hex-literal can only operate on string literals:

```rust
let hex_array = hex_literal::hex!("00010203");
```

However, if I have a file, which contains the **text** "00010203" (not binary data), and I want to calculate its hex value by

```rust
let hex_str = include_str!("path/to/hex_file");
let hex_array = hex_literal::hex!(hex_str);
```

This can't compile because "expected single string literal". What can I do to achieve this at compile time?

**Comment by tarcieri** [comment]
Seems like there could potentially be an `include_hex!` macro, although I don't know what that would actually entail

**Comment by newpavlov** [comment]
Unfortunately, as far as I know, it is not possible to do on stable right now. User-defined macros (both simple and procedural) simply expand to a bunch of code, so it's impossible to access data inside variable during macro expansion and thus we can't generate an array based on it. Ideally `hex_literal::hex` should be a `const fn`, but current Rust CTFE is not advanced enough to pull stuff like this.

So assuming you can't simply store binary files for some reason, I think the best option at the moment for you will be to use build scripts to process your hex-encoded files into binary files, which in turn will be included using `include_bytes!`. Alternatively if your constants are small enough, build script could generate an `rs` file with all your constants.

**Comment by Evian-Zhang** [comment]
> Unfortunately, as far as I know, it is not possible to do on stable right now. User-defined macros (both simple and procedural) simply expand to a bunch of code, so it's impossible to access data inside variable during macro expansion and thus we can't generate an array based on it. Ideally `hex_literal::hex` should be a `const fn`, but current Rust CTFE is not advanced enough to pull stuff like this.
> 
> So assuming you can't simply store binary files for some reason, I think the best option at the moment for you will be to use build scripts to process your hex-encoded files into binary files, which in turn will be included using `include_bytes!`. Alternatively if your constants are small enough, build script could generate an `rs` file with all your constants.

OK, thank you.
