### ISSUE TITLE
cmov: add examples defining correct usage

### ISSUE THREAD

**Issue by brxken128** [RustCrypto/utils#868]
While trying to make my Rust equality checks constant-time, I noticed that there's no examples on how to use the `cmov` crate. I understand the ASM behind it, and the core principles, but I'm unsure on how things should be structured beyond that.

For example, take these two implementations on comparing `[T]` (`[u8]` in this case):

Using `cmov` on the inner type:
```rust
impl ConstantTimeEq for u8 {
	fn ct_eq(&self, rhs: &Self) -> bool {
		let mut x = 0u8;
		x.cmovnz(1u8, u8::from(self == rhs));
		x != 0u8
	}
}

impl<T: ConstantTimeEq> ConstantTimeEq for [T] {
	fn ct_eq(&self, rhs: &Self) -> bool {
		// short-circuit if lengths don't match
		if self.len().ct_ne(&rhs.len()) {
			return false;
		}
		let mut x = 1u8;
		self.iter()
			.zip(rhs.iter())
			.for_each(|(a, b)| x.cmovz(0u8, u8::from(a.ct_eq(b))));
		x != 0u8
	}
}
```

Using `PartialEq` on the inner type:

```rust
impl<T: PartialEq> ConstantTimeEq for [T] {
	fn ct_eq(&self, rhs: &Self) -> bool {
		// short-circuit if lengths don't match
		if self.len().ct_ne(&rhs.len()) {
			return false;
		}
		let mut x = 1u8;
		self.iter()
			.zip(rhs.iter())
			.for_each(|(a, b)| x.cmovz(0u8, u8::from(a == b)));
		x != 0u8
	}
}
```

Is the first one unnecessarily complex, or is it the correct usage? It's what I'm currently testing/using for my (draft) implementation.

Out of curiosity, I tested both with `dudect_bencher`. The inner-type-`cmov` approach sat at `t ≈ +1.2`, while the `PartialEq` implementation ranged anywhere from `t ≈ +1.6` to `t = +3.67626`. Sometimes the `t` value would be negative (for both impls), however I couldn't find the definition of that anywhere.

I'd be happy to open a PR that adds some examples afterwards too!

**Comment by tarcieri** [comment]
This crate is designed for constant-time selection, not equality testing.

It seems you're trying to use it as an optimization barrier while still branching in order to do a constant-time equality comparison. It would be better to use predication instructions specifically for this case to do the comparison, rather than branching in Rust code (i.e. adding a separate trait for comparing equality using ASM, which can be built on the same predication patterns currently used).

Failing that, you should be able to use bitwise XOR and test for 0, which will tell you that the values are equal without branching.

**Comment by tarcieri** [comment]
Also I'd prefer to upstream this code to `subtle` or add `cmov` as a dependency, rather than trying to reinvent its slew of traits and impls.

**Comment by brxken128** [comment]
> This crate is designed for constant-time selection, not equality testing.
> 
> It seems you're trying to use it as an optimization barrier while still branching in order to do an equality comparison. It would be better to use predication instructions specifically for this case to do the comparison, rather than branching in Rust code (i.e. adding a separate trait for comparing equality using ASM, which can be built on the same predication patterns currently used).
> 
> Failing that, you should be able to use bitwise XOR and test for 0, which will tell you that the values are equal without branching.

I had a feeling I was missing something, and I'm very glad I asked. I wonder why `dudect` was reporting so positively.

Regarding `subtle`, I think it'd be awesome if we were able to use `cmov` as a dependency - it'd allow these (extremely helpful) core traits to be used in a wider range of applications.

I'd be happy to give implementing this a shot - which instructions do you think would be suitable?

**Comment by tarcieri** [comment]
For now you should be able to get by with XORing the values and calling `cmovz` to move a 0 in place of an initial 1 in the result.

As a micro-optimization, it should be possible to hoist the comparison up into the instructions which predication acts on. That will require separate implementations for x86 and ARM. Offhand I'm not sure what instructions (prior to `cmov*`) would be most appropriate. It currently uses a `test` instruction which performs bitwise AND.

**Comment by brxken128** [comment]
> For now you should be able to get by with XORing the values and calling `cmovz` to move a 0 in place of an initial 1 in the result.

Thank you - I think my primary issue was not understanding how/when branching occurs, and what it looks like when compiled down to ASM.

I'll have a play around with it and see how it goes! If I create something usable I'll PR it (along with the compiled ASM, `dudect` results, etc).

I think having `dudect` tests/benches in this crate would be helpful, especially if we'd like to use it within `subtle` - obviously not a requirement but additional validation never hurts.

**Comment by brxken128** [comment]
Would the options defined [here](https://doc.rust-lang.org/rust-by-example/unsafe/asm.html#options) have any adverse effects? It seems as though `cmov` is using all three - we can always just look at the compiled ASM if needs be.

**Comment by tarcieri** [comment]
Not being an expert on those options I'm not sure. I think they would probably be ok?

**Comment by brxken128** [comment]
Hopefully - I've seen them used in a few places now so I'd assume so, will double check what things compile to.

I have a working (but probably unoptimized) x86 implementation for `u8` - it works surprisingly well. Going to attempt cleaning it up and ensuring it's in-line with the rest of the crate. Should I make it a separate trait, or just an extension to the current one?

**Comment by tarcieri** [comment]
Implementation of what?

**Comment by brxken128** [comment]
> Implementation of what?

Using the `xor` ASM instruction with `cmovz` in an attempt to implement constant-time equality checks (as mentioned [here](https://github.com/RustCrypto/utils/issues/868#issuecomment-1483874207))

**Comment by tarcieri** [comment]
Aah. I'm curious if that sort of thing might be better upstreamed to `subtle`, as it feels like a slippery slope towards that crate's comparison crates

**Comment by tarcieri** [comment]
If you'd like to open an issue to discuss a constant-time equality trait, that works too

**Comment by brxken128** [comment]
I do think it would be a great extension to subtle, maybe while using this crate as a dependency (behind a feature flag). It'd arguably be easier to build on top of the ASM handling we currently have, but it all comes down to whichever you'd prefer.

I'll open a new issue to discuss it, but I'll leave this one open as I wouldn't mind adding some examples anyway.

**Comment by tarcieri** [comment]
With #872 merged I think we can close this?
