### ISSUE TITLE
[zeroize] exclude secrets from core dumps

### ISSUE THREAD

**Issue by martinetd** [RustCrypto/utils#903]
Hello,

on linux one needs to madvise(MADV_DONTDUMP) the memory used by secrets to exclude them from core dumps in the event on a crash, but I haven't seen any standard way of doing this in rust (even outside of zeroize) -- are you aware of a way of doing this?

One might argue rust programs should never crash but one could kill -SEGV or something cause such a dump and it'd go through the core dump handlers (systemd coredump, abrt or whatever), possibly on the network in corporate setup, so I usually try to protect this memory as I can in general and was surprised I couldn't figure this out without going through unsafe libc.

Thanks!

**Comment by tarcieri** [comment]
I think support for these sorts of exotic platform features is already covered in the `zeroize` FAQ: https://docs.rs/zeroize/latest/zeroize/#what-about-clearing-registers-mlock-mprotect-etc

So far we haven't pursued them in `zeroize` for simplicity's sake.

**Comment by martinetd** [comment]
Thanks for pointing me back there, I had skimmed through the doc but considered dump different enough to not realize it probably falls in the same category.. Looking back I guess you're right.
(I don't care much about live probing but I don't like much the idea of such data going to disk, which sounded orthogonal enough)

Unfortunately it says "In as much as there may be merit to these approaches, there are also many other crates that already implement more sophisticated memory protections" but I haven't been able to find any rust code that does this -- even "stricter" libs such as https://github.com/stouset/secrets just set core limit size to 0 and don't do this kind of calls...
I also just remembered memfd_secret (recent, since linux 5.14) which is actually a superset of MADV_DONTDUMP but couldn't find anything using that either... (oh, actually github code search just got me one hit -- https://github.com/CmdrMoozy/bdrck/blob/29371bfbd5c48f4ad009f46a7d7161203718e410/bdrck/src/crypto/secret.rs#L23 -- either way it'd require unsafe code just the same as madvise)


Well, not much to be done about out of scope -- my secrets don't actually matter all that much and I'll stick to zeroize, I was just curious :P
