### ISSUE TITLE
zeroize: Is it necessary to add a warning about panic abort?

### ISSUE THREAD

**Issue by stackinspector** [RustCrypto/utils#948]
When panic handling is set to abort by the "end user" (who compiles the `bin` program), the final program will abort immediately and leaves the memory cleanup to the OS. This way data that automatically or manually implements zeroize on drop is not guaranteed to be zeroize before it is cleaned up. Is there a need to warn about this in the documentation?

**Comment by tarcieri** [comment]
I guess it's a potential sharp edge but...

> the final program will abort immediately and leaves the memory cleanup to the OS.

...so it's a warning about very specific circumstances where you don't have an OS to clean up your process's memory for you.

(And then it gets further into issues like the Linux kernel is lazy and defers zeroization until the pages are allocated to a new process)

A warning may be warranted, but it's a very complicated situation to explain, especially talking about all the various ways Rust binaries could potentially be deployed, and also one that's questionably actionable (e.g. "Be careful with `panic=abort` maybe, sometimes depending on your situation")

**Comment by tarcieri** [comment]
I'm going to close this. Really the OS should clean up after terminated processes, and `zeroize` is mostly useful for providing forward secrecy while a process is running.
