### ISSUE TITLE
Update to generic-array 1.0

### ISSUE THREAD

**Issue by rukai** [RustCrypto/utils#960]
Generic-array recently released 1.0 https://github.com/fizyk20/generic-array/blob/master/CHANGELOG.md
I would love to see this dependency updated.
It does however require an MSRV of 1.65 which might be a blocker for this project.

**Comment by brxken128** [comment]
I think the plan is to migrate over fully to `hybrid-array`, so there's likely no point.

**Comment by tarcieri** [comment]
We're migrating to `hybrid-array`, which is a simple wrapper around core arrays which uses significantly less unsafe code and deeply integrates with const generics.

See #944

**Comment by rukai** [comment]
oh excellent! Sounds good to me :+1:
