### ISSUE TITLE
cpufeatures: requesting support for aarch64 target feature sm3, sm4

### ISSUE THREAD

**Issue by zonyitoo** [RustCrypto/utils#970]
ARM supports SM3, SM4 on armv8.4-A.

Linux also has `HWCAP_SM3` and `HWCAP_SM4`: https://www.kernel.org/doc/html/v5.17/arm64/elf_hwcaps.html#elf-hwcaps-index

**Comment by newpavlov** [comment]
Feel free to submit a PR. It should be a relatively trivial addition.
