### ISSUE TITLE
cmovnz and cmovz docs are confusing 

### ISSUE THREAD

**Issue by elahn** [RustCrypto/utils#990]
In the description of both `cmovnz` and `cmovz`, it says:
>conditionally moves value to self when condition is equal to zero.

The function names and first line of description convey their purpose. In the rest, it might be more clear to separate the function behaviour from instructions used to implement it.

The crate-level docs are excellent. Thank you for publishing the cmov crate! Implementing branch-free algorithms in Rust are no longer blocked on learning inline assembly.

**Comment by tarcieri** [comment]
Does #991 address your concerns?
